services:
  #NGINX
  nginx:
    build:
      context: ./nuxt
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    tty: true
    volumes:
      - ./nuxt/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      MYSQL_PASSWORD: "Kadr--1988"
      MYSQL_HOST: mysql
      MYSQL_DATABASE: "go_classic"
      MYSQL_USER: "anvarjon"
      MYSQL_ROOT_PASSWORD: "kadr1988"
    networks:
      - net_nginx
    depends_on:
      - mysql
    links:
      - mysql
  #MYSQL
  mysql:
    image: "mysql"
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'kadr1988'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'go_classic'
      MYSQL_USER: 'anvarjon'
      MYSQL_PASSWORD: 'Kadr--1988'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - vol-mysql:/var/lib/mysql
    networks:
      - net_nginx
#Declares
volumes:
  vol-mysql:
    driver: local
networks:
  net_nginx:
    driver: bridge
#  net_mysql:
#    driver: host
#    external: true
